sonar.projectKey=TimKuo0927_COMP367_GroupProject_YenTing_Umang_fromCOM313
sonar.organization=comp367-groupproject

sonar.sources=src
sonar.exclusions=node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info